[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "drf_lighten"
author = "Henock Tesfaye"
author-email = "jupiter.jupiter1@gmail.com"
classifiers = ["License :: OSI Approved :: MIT License"]
description-file = "readme.md"
